### ISSUE TITLE
也许可以参考下OpenRA

### ISSUE THREAD

**Issue by tytannial** [State-of-War-PostBar/SOW-Remastered#1]
这个想法我很久之前就有了，无奈没法解包游戏文件。😂

**Comment by taxerap** [comment]
抱歉最近一直沒時間上機所以無法及時回复……
以前是考慮過的。現在代碼尚在擱置，是否使用現成引擎還在討論。我們現在在討論遊戲邏輯，歡迎隨時到Q群裡回复參加。

**Comment by taxerap** [comment]
Already confirmed to reinvent the wheels.
