### ISSUE TITLE
所以这个项目似乎有一些我不认识的人参与?

### ISSUE THREAD

**Issue by DragoonKiller** [State-of-War-PostBar/SOW-Remastered#2]
要不报一下贴吧id或者qq?...
还有那个fork了的是谁...

**Comment by taxerap** [comment]
这个不算issue吧…
Fork的是@DubheBroken ,估计是位大神

**Comment by DragoonKiller** [comment]
不发issue难道邮件骚扰么
还有你那个所谓的计划是啥

**Comment by taxerap** [comment]
几个人讨论了一下新蓝警会是啥样，有哪些优化之类的
